name: 🐛 Bug Report
description: Report an issue or bug in any ops4life project
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! 🔍
  - type: input
    id: project
    attributes:
      label: Project
      description: Which ops4life project is this about?
      placeholder: e.g., .github, spark
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Run...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, logs, or screenshots
    validations:
      required: false
